#Assignment 3

In [1]:
#1
import pandas as pd

data = {
    'Tid': [1,2,3,4,5,6,7,8,9,10],
    'Refund': ['Yes','No','No','Yes','No','No','Yes','No','No','No'],
    'Marital_Status': ['Single','Married','Single','Married','Divorced','Married','Divorced','Single','Married','Single'],
    'Taxable_Income': [125,100,70,120,95,60,220,85,75,90],
    'Cheat': ['No','No','No','No','Yes','No','No','Yes','No','Yes']
}

df = pd.DataFrame(data)
df

   Tid Refund Marital_Status  Taxable_Income Cheat
0    1    Yes         Single             125    No
1    2     No        Married             100    No
2    3     No         Single              70    No
3    4    Yes        Married             120    No
4    5     No       Divorced              95   Yes
5    6     No        Married              60    No
6    7    Yes       Divorced             220    No
7    8     No         Single              85   Yes
8    9     No        Married              75    No
9   10     No         Single              90   Yes

In [ ]:
#2
df.loc[[0,4,7,8]]

In [ ]:
#3
df.loc[3:7] #(1)
df.iloc[4:9, 2:5] #(2)
df.iloc[:, 1:4] #(3)

In [2]:
#4
iris = pd.read_csv('Iris.csv')
iris.head()

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [3]:
#5
iris_new = iris.drop(index=4)
iris_new = iris_new.drop(iris_new.columns[3], axis=1)
iris_new

      Id  SepalLengthCm  SepalWidthCm  PetalWidthCm         Species
0      1            5.1           3.5           0.2     Iris-setosa
1      2            4.9           3.0           0.2     Iris-setosa
2      3            4.7           3.2           0.2     Iris-setosa
3      4            4.6           3.1           0.2     Iris-setosa
5      6            5.4           3.9           0.4     Iris-setosa
..   ...            ...           ...           ...             ...
145  146            6.7           3.0           2.3  Iris-virginica
146  147            6.3           2.5           1.9  Iris-virginica
147  148            6.5           3.0           2.0  Iris-virginica
148  149            6.2           3.4           2.3  Iris-virginica
149  150            5.9           3.0           1.8  Iris-virginica

[149 rows x 5 columns]

In [4]:
#6
emp_data = {
    'Employee_ID': [101,102,103,104,105],
    'Name': ['Alice','Bob','Charlie','Diana','Edward'],
    'Department': ['HR','IT','IT','Marketing','Sales'],
    'Age': [29,34,41,28,38],
    'Salary': [50000,70000,65000,55000,60000],
    'Years_of_Experience': [4,8,10,3,12],
    'Joining_Date': ['2020-03-15','2017-07-19','2013-06-01','2021-02-10','2010-11-25'],
    'Gender': ['Female','Male','Male','Female','Male'],
    'Bonus': [5000,7000,6000,4500,5000],
    'Rating': [4.5,4.0,3.8,4.7,3.5]
}

emp_df = pd.DataFrame(emp_data)
emp_df.to_csv('employees.csv', index=False)
emp_df

,Employee_ID,Name,Department,Age,Salary,Years_of_Experience,Joining_Date,Gender,Bonus,Rating
0,101,Alice,HR,29,50000,4,2020-03-15,Female,5000,4.5
1,102,Bob,IT,34,70000,8,2017-07-19,Male,7000,4.0
2,103,Charlie,IT,41,65000,10,2013-06-01,Male,6000,3.8
3,104,Diana,Marketing,28,55000,3,2021-02-10,Female,4500,4.7
4,105,Edward,Sales,38,60000,12,2010-11-25,Male,5000,3.5

In [5]:
#(a)
emp_df.shape

(5, 10)

In [6]:
#(b)
emp_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 10 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Employee_ID          5 non-null      int64
 1   Name                 5 non-null      object
 2   Department           5 non-null      object
 3   Age                  5 non-null      int64
 4   Salary               5 non-null      int64
 5   Years_of_Experience  5 non-null      int64
 6   Joining_Date         5 non-null      object
 7   Gender               5 non-null      object
 8   Bonus                5 non-null      int64
 9   Rating               5 non-null      float64
dtypes: float64(1), int64(5), object(4)
memory usage: 532.0+ bytes

In [8]:
#(c)
emp_df.describe()

,Employee_ID,Age,Salary,Years_of_Experience,Bonus,Rating
count,5.000000,5.000000,5.00000,5.000000,5.0,5.000000
mean,103.000000,34.000000,60000.00000,7.400000,5500.0,4.100000
std,1.581139,5.612486,7905.69415,3.847077,1000.0,0.494975
min,101.000000,28.000000,50000.00000,3.000000,4500.0,3.500000
25%,102.000000,29.000000,55000.00000,4.000000,5000.0,3.800000
50%,103.000000,34.000000,60000.00000,8.000000,5000.0,4.000000
75%,104.000000,38.000000,65000.00000,10.000000,6000.0,4.500000
max,105.000000,41.000000,70000.00000,12.000000,7000.0,4.700000

In [7]:
#(d)
print(emp_df.head())
print(emp_df.tail(3))

   Employee_ID     Name Department  Age  Salary  Years_of_Experience  \
0          101    Alice         HR   29   50000                    4
1          102      Bob         IT   34   70000                    8
2          103  Charlie         IT   41   65000                   10
3          104    Diana  Marketing   28   55000                    3
4          105   Edward      Sales   38   60000                   12

  Joining_Date  Gender  Bonus  Rating
0   2020-03-15  Female   5000     4.5
1   2017-07-19    Male   7000     4.0
2   2013-06-01    Male   6000     3.8
3   2021-02-10  Female   4500     4.7
4   2010-11-25    Male   5000     3.5
   Employee_ID     Name Department  Age  Salary  Years_of_Experience  \
2          103  Charlie         IT   41   65000                   10
3          104    Diana  Marketing   28   55000                    3
4          105   Edward      Sales   38   60000                   12

  Joining_Date  Gender  Bonus  Rating
2   2013-06-01    Male   6000     3.8
3   2021-02-10  Female   4500     4.7
4   2010-11-25    Male   5000     3.5

In [9]:
#(e)
avg_salary = emp_df['Salary'].mean()
total_bonus = emp_df['Bonus'].sum()
youngest_age = emp_df['Age'].min()
highest_rating = emp_df['Rating'].max()

print("average salary is", avg_salary)
print("total bonus paid is", total_bonus)
print("youngest employee age is", youngest_age)
print("highest rating is", highest_rating)

average salary is 60000.0
total bonus paid is 27500
youngest employee age is 28
highest rating is 4.7

In [10]:
#(f)
emp_df.sort_values(by='Salary', ascending=False)

,Employee_ID,Name,Department,Age,Salary,Years_of_Experience,Joining_Date,Gender,Bonus,Rating
1,102,Bob,IT,34,70000,8,2017-07-19,Male,7000,4.0
2,103,Charlie,IT,41,65000,10,2013-06-01,Male,6000,3.8
4,105,Edward,Sales,38,60000,12,2010-11-25,Male,5000,3.5
3,104,Diana,Marketing,28,55000,3,2021-02-10,Female,4500,4.7
0,101,Alice,HR,29,50000,4,2020-03-15,Female,5000,4.5

In [11]:
#(g)
def performance(rating):
    if rating >= 4.5:
        return 'Excellent'
    elif rating >= 4.0:
        return 'Good'
    else:
        return 'Average'

emp_df['Performance'] = emp_df['Rating'].apply(performance)
emp_df

,Employee_ID,Name,Department,Age,Salary,Years_of_Experience,Joining_Date,Gender,Bonus,Rating,Performance
0,101,Alice,HR,29,50000,4,2020-03-15,Female,5000,4.5,Excellent
1,102,Bob,IT,34,70000,8,2017-07-19,Male,7000,4.0,Good
2,103,Charlie,IT,41,65000,10,2013-06-01,Male,6000,3.8,Average
3,104,Diana,Marketing,28,55000,3,2021-02-10,Female,4500,4.7,Excellent
4,105,Edward,Sales,38,60000,12,2010-11-25,Male,5000,3.5,Average

In [12]:
#(h)
emp_df.isnull().sum()

Employee_ID            0
Name                   0
Department             0
Age                    0
Salary                 0
Years_of_Experience    0
Joining_Date           0
Gender                 0
Bonus                  0
Rating                 0
Performance            0
dtype: int64

In [13]:
#(i)
emp_df = emp_df.rename(columns={'Employee_ID':'ID'})
emp_df

,ID,Name,Department,Age,Salary,Years_of_Experience,Joining_Date,Gender,Bonus,Rating,Performance
0,101,Alice,HR,29,50000,4,2020-03-15,Female,5000,4.5,Excellent
1,102,Bob,IT,34,70000,8,2017-07-19,Male,7000,4.0,Good
2,103,Charlie,IT,41,65000,10,2013-06-01,Male,6000,3.8,Average
3,104,Diana,Marketing,28,55000,3,2021-02-10,Female,4500,4.7,Excellent
4,105,Edward,Sales,38,60000,12,2010-11-25,Male,5000,3.5,Average

In [14]:
#(j)
exp_more_than_5 = emp_df[emp_df['Years_of_Experience'] > 5]
it_dept = emp_df[emp_df['Department'] == 'IT']

print(exp_more_than_5)
print(it_dept)

    ID     Name Department  Age  Salary  Years_of_Experience Joining_Date  \
1  102      Bob         IT   34   70000                    8   2017-07-19
2  103  Charlie         IT   41   65000                   10   2013-06-01
4  105   Edward      Sales   38   60000                   12   2010-11-25

  Gender  Bonus  Rating Performance
1   Male   7000     4.0        Good
2   Male   6000     3.8     Average
4   Male   5000     3.5     Average
    ID     Name Department  Age  Salary  Years_of_Experience Joining_Date  \
1  102      Bob         IT   34   70000                    8   2017-07-19
2  103  Charlie         IT   41   65000                   10   2013-06-01

  Gender  Bonus  Rating Performance
1   Male   7000     4.0        Good
2   Male   6000     3.8     Average

In [15]:
#(k)
emp_df['Tax'] = emp_df['Salary'] * 0.10
emp_df

,ID,Name,Department,Age,Salary,Years_of_Experience,Joining_Date,Gender,Bonus,Rating,Performance,Tax
0,101,Alice,HR,29,50000,4,2020-03-15,Female,5000,4.5,Excellent,5000.0
1,102,Bob,IT,34,70000,8,2017-07-19,Male,7000,4.0,Good,7000.0
2,103,Charlie,IT,41,65000,10,2013-06-01,Male,6000,3.8,Average,6500.0
3,104,Diana,Marketing,28,55000,3,2021-02-10,Female,4500,4.7,Excellent,5500.0
4,105,Edward,Sales,38,60000,12,2010-11-25,Male,5000,3.5,Average,6000.0

In [16]:
#(l)
emp_df.to_csv('employees_modified.csv', index=False)
print("saved successfully")

saved successfully